# Disciplina: Ciência de Dados (DCA-0131)
Prof. Luiz Affonso Guedes

### Departamento de Engenharia de Computação e Automação - DCA

UFRN - 2022

*OBS: Favor fazer cópia do notebook antes de alterá-lo.

# Aula 2 - Computação Científica com o Pacote Numpy Python
Objetivo:

- Apresentação do Pacote Numpy para computação cietífica em Python.
- Utiliza o tipo array, que sintaticamente é bastante similar a listas, porém muito mais eficiente em termos computacionais.
sas
- Os elementos de uma variável do tipo Array em Numpy, diferentemente de listas, são do mesmo tipo.
   - Por isto, arrays são mais eficientes que listas.

### Contextualização:
- NumPy3 é o pacote básico para computação científica com o Python. 
- NumPy fornece, entre outras coisas, suporte para operações com vetores multidimensionais e funções de álgebra linear úteis. 

- Muitos outros pacotes Python usam as representações de array NumPy como uma estrutura de dados básica eficiente. 

- O pacote SciPy fornece uma coleção de algoritmos numéricos e toolboxs específicos do domínio, incluindo processamento de sinais, otimização, estatísticas e muito mais. 

- O Matplotlib é um pacote popular em Python para traçar gráficos. Este pacote utiliza o tipo array do Numpy como base.


In [2]:
# importando o pacote numpy e verificando a sua versão.
import numpy
numpy.__version__

'1.22.4'

In [3]:
# Por hábito e simplicidade, o pacote numpy é utilizado com o alias np 
import numpy as np

In [4]:
# Para verificar o conteúdo do pacote
np?

### Observação:
Não podemos esquecer que em Python todas as variáveis são tipadas dinamicamente. Assim, a cada variável é atribuída mais informação além de seu conteúdo. 
 - Como Python é implementado em C, cada variável Python é implementada como uma estrutura em C.
     - Isto acarreta alto overhead.
     - Em tipos complexo, como lista, a eficiência pode ficar muito comprometida quando se tem grandes dimensões nos dados.
     
- Assim há um dilema entre flexibilidade e desempenho:
    - Se uma lista possuir só elementos de um mesmo tipo, podemos tornar o manuseio dessa variável mais eficiente.
    - Arrays em Numpy são "listas" cujos elementos são do mesmo tipo.
        - Objeto ndarray no pacote Numpy.
    - É importante ressaltar que Python possui um tipo array, que não é o o ARRAY Numpy.

In [ ]:
# Exemplo de uso do tipo array (Não é o Array do Numpy)
import array
L = list(range(10))
print(type(L))
print(L)
print()
#A = array.array('i', L) # i designa que a variável é do tipo inteiro
A = array.array('i', L)
print(type(A))
print(A)

<class 'list'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

<class 'array.array'>
array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
# Exemplo de uso do tipo Array do Pacote Numpy (objeto ndarray)
import numpy as np
# criação e inicialização de uma variável do tipo array numpy de inteiros:
A = np.array([1, 4, 2, 5, 3])
print(type(A))
print(A)

<class 'numpy.ndarray'>
[1 4 2 5 3]


In [ ]:
# O Numpy tentará transformar todos os elementos para um mesmo tipo de dados
A2 = np.array([3.14, 4, 2, 3])
print(type(A2))
print(A2)

<class 'numpy.ndarray'>
[3.14 4.   2.   3.  ]


In [ ]:
# É Possível determinar o tipo do dado
A3 = np.array([1, 2, 3, 4], dtype='float32')
print(type(A3))
print(A3)

<class 'numpy.ndarray'>
[1. 2. 3. 4.]


In [ ]:
# Arrays em Numpy podem ser explicitamete multidimencionais
# Exemplo de iniciação de Array como lista de lista
np.array([range(i, i + 3) for i in [2, 4, 6]])
np.array([range(i, i + 4) for i in [2, 4]])

array([[2, 3, 4, 5],
       [4, 5, 6, 7]])

### Exemplos de inicializações típicas de Arrays:
- np.zeros(dimensao, dtype=tipo_de_variavel)
- np.ones(dimensao, dtype=tipo_de_variavel)
- np.full(dimensao, valor)

In [ ]:
# Exemplo de iniciação de Arrays Numpy
array1 = np.zeros(10, dtype=int)
array2 = np.ones((3, 5), dtype=float)
array3 = np.full((3, 5), 3.14)

print("array1")
print(array1)
print("array2")
print(array2)
print("array3")
print(array3)

array1
[0 0 0 0 0 0 0 0 0 0]
array2
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
array3
[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [ ]:
# Exercício 01 - crie 03 arrays Numpy
# array1, de dimensão 7 por 2, com todos elementos iguais a 2.1
# array2, vetor de dimensão 10, com todos os valores igauis a 1 em ponto flotuante
# array3, de dimensão 2 por 3 por 4, com todos os valores iguais a zero 
# escreva o código aqui

array1 = np.full((7, 2), 2.1) 
array2 = np.ones((10), dtype=float) 
array3 = np.zeros((2,3,4))

print(array1)
print(array2)
print(array3)


[[2.1 2.1]
 [2.1 2.1]
 [2.1 2.1]
 [2.1 2.1]
 [2.1 2.1]
 [2.1 2.1]
 [2.1 2.1]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
# Programa exemplificando outros tipos de iniciação de arrays numpy

print("Outros exemplos de iniciação de Arrays Numpy")
print("Infira o que faz cada tipo de iniciação")

array1 = np.arange(0, 20, 2)
array2 =np.linspace(0, 1, 5)
array3 = np.eye(3)

print("array1")
print(array1)
print("array2")
print(array2)
print("array3")
print(array3)

Outros exemplos de iniciação de Arrays Numpy
Infira o que faz cada tipo de iniciação
array1
[ 0  2  4  6  8 10 12 14 16 18]
array2
[0.   0.25 0.5  0.75 1.  ]
array3
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Exemplo de iniciação de um array numpy de forma randômica

print("Os Arrays NumPy também podem ser inicializados de forma randômica")
media = 0
desvio_padrao = 1
num_linhas = 3
num_colunas = 3
inicio = 0 # início do intervalo da distribuição linear - fechado
fim = 2    # fim do intervalo da distribuição linear - aberto
           # o intervalo é [inicio, fim)

array1 = np.random.normal(media,desvio_padrao, (num_linhas, num_colunas))
array2 = np.random.random((num_linhas, num_colunas))
array3 = np.random.randint(inicio,fim, (num_linhas, num_colunas))

print("array1 - Iniciação randômica seguindo distribuição Normal")
print(array1)
print("array2 - Iniciação randômica seguindo distribuição Uniforme ente 0 e 1")
print(array2)
print("array3 - Iniciação randômica com números inteiros")
print(array3)

Os Arrays NumPy também podem ser inicializados de forma randômica
array1 - Iniciação randômica seguindo distribuição Normal
[[ 0.99723934 -0.94302363  0.01148488]
 [ 1.99328704  1.04669973  1.01424954]
 [ 0.80946479  1.30352136  0.02069935]]
array2 - Iniciação randômica seguindo distribuição Uniforme ente 0 e 1
[[0.57524235 0.5169687  0.73342011]
 [0.27736116 0.79774316 0.66006452]
 [0.76006401 0.2986103  0.70820034]]
array3 - Iniciação randômica com números inteiros
[[0 0 1]
 [1 0 0]
 [0 0 1]]


In [ ]:
# Exemplos de iniciação randômica de arrays Numpy, porém com semente definida.
import numpy as np

np.random.seed(0) # Iniciação da semente randômica
x1 = np.random.randint(10, size=6) # Array unidimensional
x2 = np.random.randint(10, size=(3, 4)) # Array bi-dimensional
x3 = np.random.randint(10, size=(3, 4, 5)) # Array tri-dimensional

print(x1) 
print('\naqui comecça o x2')
print(x2)
print('\naqui comecça o x3')
print(x3)

print('\nExemplos de métodos para informar os tipos de dados dos Arrays\n')

print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("x3 dtype:", x3.dtype)
print("x3 itemsize:", x3.itemsize, "bytes")
print("x3 nbytes:", x3.nbytes, "bytes")

[5 0 3 3 7 9]

aqui comecça o x2
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

aqui comecça o x3
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]

Exemplos de métodos para informar os tipos de dados dos Arrays

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
x3 dtype: int64
x3 itemsize: 8 bytes
x3 nbytes: 480 bytes


### Acesso de elementos e seguimentos de Array Numpy
- Segue o mesmo modo de acesso de elementos em lista

In [ ]:
# Array x1, definido anteriormente
print(x1)
print(type(x1))
x1

[5 0 3 3 7 9]
<class 'numpy.ndarray'>


array([5, 0, 3, 3, 7, 9])

In [ ]:
# Exemplos de acesso de elementos de um array Numpy unidimensional
print("Array x1 --> ", x1)
print("x1[0] = ", x1[0])
print("x1[-1] = ", x1[-1])
print("x1[-2] = ", x1[-2])
# print("x1[-7] = ", x1[-7])  # Isto irá funcionar??? resposta: Não irá

Array x1 -->  [5 0 3 3 7 9]
x1[0] =  5
x1[-1] =  9
x1[-2] =  7


In [ ]:
# Array x2, definido anteriormente
print(x2)
print(type(x2))


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
<class 'numpy.ndarray'>


In [ ]:
# Exemplos de acesso de elementos de um array Numpy multidimensional
print("x2[0,0]  = ", x2[0,0])
print("x2[2,-1] =  ",x2[2,-1])
x2[0,0] = 10
x2[2,-1] = 2.345
print(x2)
print("x2[0,0]  = ", x2[0,0])
print("x2[2,-1] =  ",x2[2,-1])  # será um número inteiro ou ponto flutuante?

x2[0,0]  =  3
x2[2,-1] =   7
[[10  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  2]]
x2[0,0]  =  10
x2[2,-1] =   2


In [ ]:
# Exemplos de acesso de sub-arraays de um array Numpy unidimensional
x = np.arange(10)
print("x       = ", x)
print("x[0:2]  = ", x[0:2])
print("x[2:-1] = ", x[2:-1])
print("x[:-1]  = ", x[:-1])
print("x[1:]   = ", x[1:])
print("x[:]    = ", x[:])

x       =  [0 1 2 3 4 5 6 7 8 9]
x[0:2]  =  [0 1]
x[2:-1] =  [2 3 4 5 6 7 8]
x[:-1]  =  [0 1 2 3 4 5 6 7 8]
x[1:]   =  [1 2 3 4 5 6 7 8 9]
x[:]    =  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Exemplos de acesso de vários elementos um array Numpy unidimensional
x = np.arange(10)
print("x       = ", x)
print()
print("x[::2]  = ", x[::2]) # acesso desde o primeiro elemento com passo 2
print("x[::3]  = ", x[::3]) # acesso desde o primeiro elemento com passo 3
print("x[1::2] = ", x[1::2]) # acesso desde o segundo elemento com passo 2
print("x[::-1] = ", x[::-1]) # acesso os elemento de modo reverso
print("x[6::-2]= ", x[6::-2]) # acesso desde o sexto os elemento com passo -2
print()
print("x[4:8:-2]= ", x[4:8:-2]) # ????
print()
print("x[1:8:2]= ", x[1:8:2]) # caso geral


x       =  [0 1 2 3 4 5 6 7 8 9]

x[::2]  =  [0 2 4 6 8]
x[::3]  =  [0 3 6 9]
x[1::2] =  [1 3 5 7 9]
x[::-1] =  [9 8 7 6 5 4 3 2 1 0]
x[6::-2]=  [6 4 2 0]

x[4:8:-2]=  []

x[1:8:2]=  [1 3 5 7]


In [ ]:
# Exemplo de acesso de sub-arrays de um array Numpy multidimensional
print("x2 = ")
print(x2)

x2 = 
[[10  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  2]]


In [ ]:
# Exemplo de acesso de sub-arrays de um array Numpy multidimensional
print("x2[:2, :3] = ")
print(x2[:2, :3])

x2[:2, :3] = 
[[3 5 2]
 [7 6 8]]


In [ ]:
# Exemplo de acesso de sub-arrays de um array Numpy multidimensional
print("x2[:3, ::2] = ")
print(x2[:3, ::2])


x2[:3, ::2] = 
[[3 2]
 [7 8]
 [1 7]]


In [ ]:
# Exemplo de acesso de sub-arrays de um array Numpy multidimensional
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
# Exercício - Obtenha de sub-arrays multidimensionais
print("Dada a matriz x2")
print("Obter uma sub matriz que corresponde às linhas ímpares e as colunas pares, escritas de modo reservo.")
# início do código
print(x2[1:2, 8::-3])

# fim do código

Dada a matriz x2
Obter uma sub matriz que corresponde às linhas ímpares e as colunas pares, escritas de modo reservo.
[[8 7]]


### Observação:
Um ponto muito importante a ser observado é que sub-arrays em Numpy não fazem cópia do array original, mas sim são visões deles(referências aos mesmos espaços de endereço).
- Isto se deve por questão de eficiência.
- Em lista, ao contrário de Arrays, sub-listas são cópias de elementos da lista original.

Os exemplos abaixo evidenciam isto.

In [ ]:
# Exemplos de sub-arrays como vistas dos arrays originais
print("x2 = ")
print(x2)

x2_sub = x2[:2, :2]
print()
print("x2_sub")
print(x2_sub)

x2_sub[0, 0] = 99
print()
print("x2_sub[0, 0] = 99")
print(x2_sub)

print("")
print("Novos valores para x2")
print("x2 = ")
print(x2)

x2 = 
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

x2_sub
[[3 5]
 [7 6]]

x2_sub[0, 0] = 99
[[99  5]
 [ 7  6]]

Novos valores para x2
x2 = 
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
#Como, então, se pode fazer cópia de arrays Numpy?

Como, então, se pode fazer cópia de arrays Numpy?


In [ ]:
print("Cópias de Arrays Numpy são realizados via o método .copy()")
print("x2 = ")
print(x2)

x2_sub_copy = x2[:2, :2].copy()
print()
print("x2_sub_copy")
print(x2_sub_copy)

x2_sub_copy[0, 0] = 42
print()
print("x2_sub_cop - atribuir 42 para a posição [0,0]")
print(x2_sub_copy)

print()
print("Verificação dos valores de x2")
print(x2)

Cópias de Arrays Numpy são realizados via o método .copy()
x2 = 
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

x2_sub_copy
[[99  5]
 [ 7  6]]

x2_sub_cop - atribuir 42 para a posição [0,0]
[[42  5]
 [ 7  6]]

Verificação dos valores de x2
[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [ ]:
# Concatenação de Arrays Numpy

x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6,7,8,9])
w = np.concatenate([x, y,z])
print("w = ")
print(w)

w = 
[1 2 3 4 5 6 7 8 9]


In [ ]:
# Concatenação de Arrays bidimensionais Numpy - Matrizes
mat1 = np.array([[1, 2, 3],[4, 5, 6]])
print("mat1 = ")
print(mat1)

mat2 = np.concatenate([mat1,mat1])
print()
print("mat2 = ")
print(mat2)

mat3 = np.concatenate([mat1,mat1], axis=1)
print()
print("mat3 = ")
print(mat3)

mat1 = 
[[1 2 3]
 [4 5 6]]

mat2 = 
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]

mat3 = 
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [ ]:
# Separando Arrays Numpy
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
x1, x2, x3 = np.split(x, [3, 5])
print("x1, x2, x3")
print(x1, x2, x3)

y1, y2, y3, y4 = np.split(x, [2, 5, 7])
print("y1, y2, y3, y4")
print(y1, y2, y3, y4)


x1, x2, x3
[1 2 3] [4 5] [6 7 8 9]
y1, y2, y3, y4
[1 2] [3 4 5] [6 7] [8 9]


In [ ]:
# Exercício - Divida o array vet em outros 5 arrays de mesmo tamanho

vet = [1,2,3,4,5,6,7,8,9,10]
x1, x2, x3, x4, x5 = np.split(vet,[2,4,6,8])
print(x1, x2, x3, x4, x5 )

[1 2] [3 4] [5 6] [7 8] [ 9 10]


### Programando eficientemente em Python
- Python é uma linguagem interpretada, escrita em C.
- Chamadas de métodos em Python levam a chamadas de funções em C.
- Programação vetorizada aumenta consideravelmente o desempenho dos programas Python.
    - usa funções com tipos pré-tipados

In [ ]:
# Exemplo de programação estilo escalar 
# Função para obter os valores recíprocos (inversos) dos elementos de um Array Numpy

import numpy as np

np.random.seed(0)   # semente

def calcular_reciprocos(values):
  output = np.empty(len(values))
  for i in range(len(values)):
   output[i] = 1.0 / values[i]
  return output

valores = np.random.randint(1, 10, size=5)
valores_inversos = calcular_reciprocos(valores)
print(valores_inversos)

[0.16666667 1.         0.25       0.25       0.125     ]


In [ ]:
# Exemplo - Medição de tempo gasto para executar a função calcular_reciprocos(.) 
big_array = np.random.randint(1, 100, size=1000000)
%timeit calcular_reciprocos(big_array)

2.96 s ± 1.47 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
# Exemplo de programação vetorizada

print(calcular_reciprocos(valores))  # programação escalar
print()
print(1.0 / valores)                 # programação vetorizada


[0.16666667 1.         0.25       0.25       0.125     ]

[0.16666667 1.         0.25       0.25       0.125     ]


In [ ]:
# Exemplo: medição de tempo de programação vetorizada
%timeit (1.0 / big_array)

1.61 ms ± 169 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# Exemplo de programação vetorizada
print("Você pode explicar o que faz a linha de código abaixo?")
x = 2 ** np.arange(9)
x1 = x.reshape((3, 3))
x1

Você pode explicar o que faz a linha de código abaixo?
<class 'numpy.ndarray'>


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [ ]:
# Exemplo de programação vetorizada
print("Você pode explicar o que faz a linha de código abaixo?")
x = 2 ** np.arange(9).reshape((3, 3))
x

Você pode explicar o que faz a linha de código abaixo?


array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [ ]:
# Exemplo de programação vetorizada
print("Você pode explicar o que faz a linha de código abaixo?")
x =  np.arange(9).reshape((3, 3)) ** 2
x

Você pode explicar o que faz a linha de código abaixo?


array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
# Exemplo de programação vetorizada
print("Você pode explicar o que faz a linha de código abaixo?")
x = np.arange(4).reshape((2, 2)) ** np.arange(4).reshape((2, 2))
x

Você pode explicar o que faz a linha de código abaixo?


array([[ 1,  1],
       [ 4, 27]])

In [ ]:
# Exemplo de programação vetorizada
print("Você pode explicar o que faz a linha de código abaixo?")
x = 2 ** np.arange(8).reshape((2,2,2))
x

Você pode explicar o que faz a linha de código abaixo?


array([[[  1,   2],
        [  4,   8]],

       [[ 16,  32],
        [ 64, 128]]])

### Os operadores matemáticos em Numpy operam elemento-a-elemento
- Mais a frente veremos como implementar operações matriciais, no estilo Matlab.
- Exemplos de operadores matemáticos sobre arrays
        - +, - , *,/, **, //, % 


In [ ]:
# Exemplo de programação vetorizada

x = np.array([0,1,2,3])
y1 = 2*x[::2]
y2 = x * 2
y3 = x * x
y4 = x ** x
print("x = ")
print(x)
print()
print("x + 10 = ")
print(x + 10)
print()
print("-(0.5*x) + 2 = ")
print(-(0.5*x) + 2 )
print()
print("y1 = ")
print(y1)
print()
print("y2 = ")
print(y2)
print()
print("y3 = ")
print(y3)
print()
print("y4 = ")
print(y4)

x = 
[0 1 2 3]

x + 10 = 
[10 11 12 13]

-(0.5*x) + 2 = 
[2.  1.5 1.  0.5]

y1 = 
[0 4]

y2 = 
[0 2 4 6]

y3 = 
[0 1 4 9]

y4 = 
[ 1  1  4 27]


### Operadores matemáticos são chamadas de métodos em Numpy
- Operador Adição (+) , equivale a np.add Addition (por exemplo, 1 + 1 = 2)
- Operador Subtração (-),equivale a np.subtract Subtraction (por exemplo, 3 - 2 = 1)
- Operador Nagativo Unário (-), equivale a np.negative (por exemplo, -2)
- Operador Multiplicação (*), equivale a np.multiply (por exemplo, 2 * 3 = 6)
- Operador Divisão (/), equivale a np.divide (por exemplo, 3 / 2 = 1.5)
- Operador Divisão Inteira (//), equivale a np.floor_divide (por exemplo, 7 // 2 = 3)
- Operador Exponenciação, equivale a np.power
- Operador módulo (%), equivale a np.mod (por exemplo, 7 % 2 = 1)

In [ ]:
# Exemplos de métodos associados com operadores
print("x = ")
print(x)

print()
print("x + 10 = ")
print(np.add(x, 10))

print()
print("x ** 2 = ")
print(np.power(x, 2))


x = 
[0 1 2 3]

x + 10 = 
[10 11 12 13]

x ** 2 = 
[0 1 4 9]


In [ ]:
# Exemplo de método associado com operador multiplicação com especificação da variável de saída
x = np.arange(5)
y = np.empty(5)   # cria um array de 5 posições
print(y)
np.multiply(x, 10, out=y)
# y = np.multiply(x, 10)
print(y)

[0.16666667 1.         0.25       0.25       0.125     ]
[ 0. 10. 20. 30. 40.]


### Numpy possui um rico suporte de funções e constantes mataméticas.
- Exemplos de funções de Trigonometria:
        - valor de pi --> np.pi
        - valor de e --> np.e
        - função seno --> np.sin(radiano)
        - função cosseno --> np.cos(radiano)
        - função tangente --> np.tan(radiano)
        - função arcoseno -->  np.arcsin(radiano)
        - função arcocosseno -->  np.arccos(radiano)
        - função arcotangente --> np.arctan(radiano)

In [ ]:
# Exemplos de uso de funções trigonométricas em Numpy
print("Valor de PI --> ", np.pi)
print( "Valor de e --> ", np.e)
print( "Valor de seno(pi/2) --> ", np.sin(np.pi/2)) 

teta = np.array([0, np.pi/4, np.pi/2, np.pi*3/4, np.pi])
print("Valor de teta = ")
print(teta)
print("Valor de seno(teta) = ")
print(np.sin(teta))

Valor de PI -->  3.141592653589793
Valor de e -->  2.718281828459045
Valor de seno(pi/2) -->  1.0
Valor de teta = 
[0.         0.78539816 1.57079633 2.35619449 3.14159265]
Valor de seno(teta) = 
[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]


### Exercício:
Dada a seguinte equação: 
$\newcommand{\sen}{{\rm sen}}$

$ y = \sqrt[2]{1 - \sen^2(k.\pi/4)} $



In [ ]:
# Exercício - Calcule e imprima o valor de y
# Sem utilização do comando for

#k = np.array(range(8))
k = np.arange(8)
# Calcule o valor de y via equação descrita acima.

y = np.sqrt(1 - np.sin(k*np.pi/4)**2)

print(k)
print(y)

[0 1 2 3 4 5 6 7]
[1.         0.70710678 0.         0.70710678 1.         0.70710678
 0.         0.70710678]


In [5]:
# Exercício - Calcule e imprima o IMC dos alunos
# 01 polegada = 2.54 cm = 0.0254 m
# 01 libra = 0.453592 Kg
# Altura dos alunos em polegadas

altura_polegada = [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73, 75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74, 72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72, 75, 75, 75, 75, 68, 74, 78, 71, 73, 76, 74, 74, 79, 75, 73, 76, 74, 74, 73, 72, 74, 73, 74, 72, 73, 69, 72, 73, 75, 75, 73, 72, 72, 76, 74, 72, 77, 74, 77, 75, 76, 80, 74, 74, 75, 78, 73, 73, 74, 75, 76, 71, 73, 74, 76, 76, 74, 73, 74, 70, 72, 73, 73, 73, 73, 71, 74, 74, 72, 74, 71, 74, 73, 75, 75, 79, 73, 75, 76, 74, 76, 78, 74, 76, 72, 74, 76, 74, 75, 78, 75, 72, 74, 72, 74, 70, 71, 70, 75, 71, 71, 73, 72, 71, 73, 72, 75, 74, 74, 75, 73, 77, 73, 76, 75, 74, 76, 75, 73, 71, 76, 75, 72, 71, 77, 73, 74, 71, 72, 74, 75, 73, 72, 75, 75, 74, 72, 74, 71, 70, 74, 77, 77, 75, 75, 78, 75, 76, 73, 75, 75, 79, 77, 76, 71, 75, 74, 69, 71, 76, 72, 72, 70, 72, 73, 71, 72, 71, 73, 72, 73, 74, 74, 72, 75, 74, 74, 77, 75, 73, 72, 71, 74, 77, 75, 75, 75, 78, 78, 74, 76, 78, 76, 70, 72, 80, 74, 74, 71, 70, 72, 71, 74, 71, 72, 71, 74, 69, 76, 75, 75, 76, 73, 76, 73, 77, 73, 72, 72, 77, 77, 71, 74, 74, 73, 78, 75, 73, 70, 74, 72, 73, 73, 75, 75, 74, 76, 73, 74, 75, 75, 72, 73, 73, 72, 74, 78, 76, 73, 74, 75, 70, 75, 71, 72, 78, 75, 73, 73, 71, 75, 77, 72, 69, 73, 74, 72, 70, 75, 70, 72, 72, 74, 73, 74, 76, 75, 80, 72, 75, 73, 74, 74, 73, 75, 75, 71, 73, 75, 74, 74, 72, 74, 74, 74, 73, 76, 75, 72, 73, 73, 73, 72, 72, 72, 72, 71, 75, 75, 74, 73, 75, 79, 74, 76, 73, 74, 74, 72, 74, 74, 75, 78, 74, 74, 74, 77, 70, 73, 74, 73, 71, 75, 71, 72, 77, 74, 70, 77, 73, 72, 76, 71, 76, 78, 75, 73, 78, 74, 79, 75, 76, 72, 75, 75, 70, 72, 70, 74, 71, 76, 73, 76, 71, 69, 72, 72, 69, 73, 69, 73, 74, 74, 72, 71, 72, 72, 76, 76, 76, 74, 76, 75, 71, 72, 71, 73, 75, 76, 75, 71, 75, 74, 72, 73, 73, 73, 73, 76, 72, 76, 73, 73, 73, 75, 75, 77, 73, 72, 75, 70, 74, 72, 80, 71, 71, 74, 74, 73, 75, 76, 73, 77, 72, 73, 77, 76, 71, 75, 73, 74, 77, 71, 72, 73, 69, 73, 70, 74, 76, 73, 73, 75, 73, 79, 74, 73, 74, 77, 75, 74, 73, 77, 73, 77, 74, 74, 73, 77, 74, 77, 75, 77, 75, 71, 74, 70, 79, 72, 72, 70, 74, 74, 72, 73, 72, 74, 74, 76, 82, 74, 74, 70, 73, 73, 74, 77, 72, 76, 73, 73, 72, 74, 74, 71, 72, 75, 74, 74, 77, 70, 71, 73, 76, 71, 75, 74, 72, 76, 79, 76, 73, 76, 78, 75, 76, 72, 72, 73, 73, 75, 71, 76, 70, 75, 74, 75, 73, 71, 71, 72, 73, 73, 72, 69, 73, 78, 71, 73, 75, 76, 70, 74, 77, 75, 79, 72, 77, 73, 75, 75, 75, 73, 73, 76, 77, 75, 70, 71, 71, 75, 74, 69, 70, 75, 72, 75, 73, 72, 72, 72, 76, 75, 74, 69, 73, 72, 72, 75, 77, 76, 80, 77, 76, 79, 71, 75, 73, 76, 77, 73, 76, 70, 75, 73, 75, 70, 69, 71, 72, 72, 73, 70, 70, 73, 76, 75, 72, 73, 79, 71, 72, 74, 74, 74, 72, 76, 76, 72, 72, 71, 72, 72, 70, 77, 74, 72, 76, 71, 76, 71, 73, 70, 73, 73, 72, 71, 71, 71, 72, 72, 74, 74, 74, 71, 72, 75, 72, 71, 72, 72, 72, 72, 74, 74, 77, 75, 73, 75, 73, 76, 72, 77, 75, 72, 71, 71, 75, 72, 73, 73, 71, 70, 75, 71, 76, 73, 68, 71, 72, 74, 77, 72, 76, 78, 81, 72, 73, 76, 72, 72, 74, 76, 73, 76, 75, 70, 71, 74, 72, 73, 76, 76, 73, 71, 68, 71, 71, 74, 77, 69, 72, 76, 75, 76, 75, 76, 72, 74, 76, 74, 72, 75, 78, 77, 70, 72, 79, 74, 71, 68, 77, 75, 71, 72, 70, 72, 72, 73, 72, 74, 72, 72, 75, 72, 73, 74, 72, 78, 75, 72, 74, 75, 75, 76, 74, 74, 73, 74, 71, 74, 75, 76, 74, 76, 76, 73, 75, 75, 74, 68, 72, 75, 71, 70, 72, 73, 72, 75, 74, 70, 76, 71, 82, 72, 73, 74, 71, 75, 77, 72, 74, 72, 73, 78, 77, 73, 73, 73, 73, 73, 76, 75, 70, 73, 72, 73, 75, 74, 73, 73, 76, 73, 75, 70, 77, 72, 77, 74, 75, 75, 75, 75, 72, 74, 71, 76, 71, 75, 76, 83, 75, 74, 76, 72, 72, 75, 75, 72, 77, 73, 72, 70, 74, 72, 74, 72, 71, 70, 71, 76, 74, 76, 74, 74, 74, 75, 75, 71, 71, 74, 77, 71, 74, 75, 77, 76, 74, 76, 72, 71, 72, 75, 73, 68, 72, 69, 73, 73, 75, 70, 70, 74, 75, 74, 74, 73, 74, 75, 77, 73, 74, 76, 74, 75, 73, 76, 78, 75, 73, 77, 74, 72, 74, 72, 71, 73, 75, 73, 67, 67, 76, 74, 73, 70, 75, 70, 72, 77, 79, 78, 74, 75, 75, 78, 76, 75, 69, 75, 72, 75, 73, 74, 75, 75, 73]
peso_libra = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185, 160, 180, 185, 189, 185, 219, 230, 205, 230, 195, 180, 192, 225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185, 175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270, 200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170, 230, 155, 185, 185, 200, 225, 225, 220, 160, 205, 235, 250, 210, 190, 160, 200, 205, 222, 195, 205, 220, 220, 170, 185, 195, 220, 230, 180, 220, 180, 180, 170, 210, 215, 200, 213, 180, 192, 235, 185, 235, 210, 222, 210, 230, 220, 180, 190, 200, 210, 194, 180, 190, 240, 200, 198, 200, 195, 210, 220, 190, 210, 225, 180, 185, 170, 185, 185, 180, 178, 175, 200, 204, 211, 190, 210, 190, 190, 185, 290, 175, 185, 200, 220, 170, 220, 190, 220, 205, 200, 250, 225, 215, 210, 215, 195, 200, 194, 220, 180, 180, 170, 195, 180, 170, 206, 205, 200, 225, 201, 225, 233, 180, 225, 180, 220, 180, 237, 215, 190, 235, 190, 180, 165, 195, 200, 190, 190, 185, 185, 205, 190, 205, 206, 220, 208, 170, 195, 210, 190, 211, 230, 170, 185, 185, 241, 225, 210, 175, 230, 200, 215, 198, 226, 278, 215, 230, 240, 184, 219, 170, 218, 190, 225, 220, 176, 190, 197, 204, 167, 180, 195, 220, 215, 185, 190, 205, 205, 200, 210, 215, 200, 205, 211, 190, 208, 200, 210, 232, 230, 210, 220, 210, 202, 212, 225, 170, 190, 200, 237, 220, 170, 193, 190, 150, 220, 200, 190, 185, 185, 200, 172, 220, 225, 190, 195, 219, 190, 197, 200, 195, 210, 177, 220, 235, 180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200, 190, 180, 205, 220, 190, 215, 235, 191, 200, 181, 200, 210, 240, 185, 165, 190, 185, 175, 155, 210, 170, 175, 220, 210, 205, 200, 205, 195, 240, 150, 200, 215, 202, 200, 190, 205, 190, 160, 215, 185, 200, 190, 210, 185, 220, 190, 202, 205, 220, 175, 160, 190, 200, 229, 206, 220, 180, 195, 175, 188, 230, 190, 200, 190, 219, 235, 180, 180, 180, 200, 234, 185, 220, 223, 200, 210, 200, 210, 190, 177, 227, 180, 195, 199, 175, 185, 240, 210, 180, 194, 225, 180, 205, 193, 230, 230, 220, 200, 249, 190, 208, 245, 250, 160, 192, 220, 170, 197, 155, 190, 200, 220, 210, 228, 190, 160, 184, 180, 180, 200, 176, 160, 222, 211, 195, 200, 175, 206, 240, 185, 260, 185, 221, 205, 200, 170, 201, 205, 185, 205, 245, 220, 210, 220, 185, 175, 170, 180, 200, 210, 175, 220, 206, 180, 210, 195, 200, 200, 164, 180, 220, 195, 205, 170, 240, 210, 195, 200, 205, 192, 190, 170, 240, 200, 205, 175, 250, 220, 224, 210, 195, 180, 245, 175, 180, 215, 175, 180, 195, 230, 230, 205, 215, 195, 180, 205, 180, 190, 180, 190, 190, 220, 210, 255, 190, 230, 200, 205, 210, 225, 215, 220, 205, 200, 220, 197, 225, 187, 245, 185, 185, 175, 200, 180, 188, 225, 200, 210, 245, 213, 231, 165, 228, 210, 250, 191, 190, 200, 215, 254, 232, 180, 215, 220, 180, 200, 170, 195, 210, 200, 220, 165, 180, 200, 200, 170, 224, 220, 180, 198, 240, 239, 185, 210, 220, 200, 195, 220, 230, 170, 220, 230, 165, 205, 192, 210, 205, 200, 210, 185, 195, 202, 205, 195, 180, 200, 185, 240, 185, 220, 205, 205, 180, 201, 190, 208, 240, 180, 230, 195, 215, 190, 195, 215, 215, 220, 220, 230, 195, 190, 195, 209, 204, 170, 185, 205, 175, 210, 190, 180, 180, 160, 235, 200, 210, 180, 190, 197, 203, 205, 170, 200, 250, 200, 220, 200, 190, 170, 190, 220, 215, 206, 215, 185, 235, 188, 230, 195, 168, 190, 160, 200, 200, 189, 180, 190, 200, 220, 187, 240, 190, 180, 185, 210, 220, 219, 190, 193, 175, 180, 215, 210, 200, 190, 185, 220, 170, 195, 205, 195, 210, 190, 190, 180, 220, 190, 186, 185, 190, 180, 190, 170, 210, 240, 220, 180, 210, 210, 195, 160, 180, 205, 200, 185, 245, 190, 210, 200, 200, 222, 215, 240, 170, 220, 156, 190, 202, 221, 200, 190, 210, 190, 200, 165, 190, 185, 230, 208, 209, 175, 180, 200, 205, 200, 250, 210, 230, 244, 202, 240, 200, 215, 177, 210, 170, 215, 217, 198, 200, 220, 170, 200, 230, 231, 183, 192, 167, 190, 180, 180, 215, 160, 205, 223, 175, 170, 190, 240, 175, 230, 223, 196, 167, 195, 190, 250, 190, 190, 190, 170, 160, 150, 225, 220, 209, 210, 176, 260, 195, 190, 184, 180, 195, 195, 219, 225, 212, 202, 185, 200, 209, 200, 195, 228, 210, 190, 212, 190, 218, 220, 190, 235, 210, 200, 188, 210, 235, 188, 215, 216, 220, 180, 185, 200, 210, 220, 185, 231, 210, 195, 200, 205, 200, 190, 250, 185, 180, 170, 180, 208, 235, 215, 244, 220, 185, 230, 190, 200, 180, 190, 196, 180, 230, 224, 160, 178, 205, 185, 210, 180, 190, 200, 257, 190, 220, 165, 205, 200, 208, 185, 215, 170, 235, 210, 170, 180, 170, 190, 150, 230, 203, 260, 246, 186, 210, 198, 210, 215, 180, 200, 245, 200, 192, 192, 200, 192, 205, 190, 186, 170, 197, 219, 200, 220, 207, 225, 207, 212, 225, 170, 190, 210, 230, 210, 200, 238, 234, 222, 200, 190, 170, 220, 223, 210, 215, 196, 175, 175, 189, 205, 210, 180, 180, 197, 220, 228, 190, 204, 165, 216, 220, 208, 210, 215, 195, 200, 215, 229, 240, 207, 205, 208, 185, 190, 170, 208, 225, 190, 225, 185, 180, 165, 240, 220, 212, 163, 215, 175, 205, 210, 205, 208, 215, 180, 200, 230, 211, 230, 190, 220, 180, 205, 190, 180, 205, 190, 195]
# ----------------- cálculo do IMC  ----------------------

peso = np.multiply(np.array(peso_libra), 0.453592)
altura = np.multiply(np.array(altura_polegada), 0.0254)


IMC = np.divide(peso,altura**2)

# --------------------------------------------------------
print("Os valores de IMC dos alunos são:")
print(IMC)

Os valores de IMC dos alunos são:
[23.11037639 27.60406069 28.48080465 ... 25.62295933 23.74810865
 25.72686361]


### Exemplos de funções exponenciais e logorítmicas
- $\ e^x$ = $exp(x)$ --> np.exp(array)
- $2^x$ --> np.exp2(array)
- $b^e$ --> np.power(array_base, array_expoente)
- $ln(x)$ --> np.log(array)
- $log_2(x)$ --> np.log2(array)
- $log_{10}(x)$ --> np.log10(array)

In [6]:
# Exemplos de uso de funções exponenciais
x = [1, 2, 3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(2, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [2 4 8]


In [8]:
# Exemplos de uso de funções exponenciais

#print("e^x =", np.e**x)  # esta expressão está correta?

print( "e^x =", (np.e*np.ones(3))**x)

e^x = [ 2.71828183  7.3890561  20.08553692]


In [9]:
# Exemplos de uso de funções logorítmicas
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


### Operações "recursivas" em Arrays Numpy
- Executam elemento-a-elemento recorrentemente, até percorrer todo o array.
- np.add.reduce(array) --> retorna a somatória dos elementos do array  
- np.multiply.reduce(array) --> retorna o produtório dos elementos do array 

In [10]:
# Exemplos de uso do método reduce()
x = np.arange(1,5)
y1 = np.add.reduce(x)
y2 = np.multiply.reduce(x)

print("x = ", x)
print("y1 = ", y1)
print("y2 = ", y2)


x =  [1 2 3 4]
y1 =  10
y2 =  24


In [11]:
# Exemplos de uso do método .accumulate(array)
print("Que procedimento o método '.accumulate(array)' executa?")
y3 = np.add.accumulate(x)
y4 = np.multiply.accumulate(x)

print("x = ", x)
print("y3 = ", y3)
print("y4 = ", y4)

Que procedimento o método '.accumulate(array)' executa?
x =  [1 2 3 4]
y3 =  [ 1  3  6 10]
y4 =  [ 1  2  6 24]


In [12]:
# Exemplos de uso do método .outer(array1, array2)
print("O que procedimento o método '.outer(array1, array2)' executa?")
x = np.arange(1,5)
x1 = np.ones(5)
y5 = np.add.outer(x, x)
y6 = np.multiply.outer(x, x)
y7 = np.add.outer(x, x1)

print("x = ", x,"\n")
print("x1 = ", x1,"\n")
print("y5 = ")
print(y5,"\n")
print("y6 = ")
print(y6, "\n")
print("y7 = ")
print(y7)

O que procedimento o método '.outer(array1, array2)' executa?
x =  [1 2 3 4] 

x1 =  [1. 1. 1. 1. 1.] 

y5 = 
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 

y6 = 
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]] 

y7 = 
[[2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]]


### Observação:
Operadores aritiméticos e lógicos entre Arrays Numpy e escalares são aplicados elemento-a-elemento no Array.

De forma geral, é possível realizar operações aritiméticas e lógicas com array de dimensões diferentes.
- a operação será reaizada por dimensão.

In [13]:
# Exemplos de operações aritiméticas e lógicas com Array Numpy e escalares
x = np.array([1, 2, 3, 4, 5])
print("x < 3 \n", x<3)
print("x == 3 \n", x==3)
print("x + 3 \n", x+3)
print("x * 3 \n", x*3)
print("x / 3 \n", x/3)

x < 3 
 [ True  True False False False]
x == 3 
 [False False  True False False]
x + 3 
 [4 5 6 7 8]
x * 3 
 [ 3  6  9 12 15]
x / 3 
 [0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [14]:
print(x[:4].sum())
print(sum(x<3))
x[x<5].sum()

10
2


10

In [18]:
# Exemplos de operações aritiméticas e lógicas 
# entre Array bidimensional e unidimensional
x1 = np.array([[1, 2, 3], [4, 5, 6]])
x2 = np.array([2,2,2])
print("x1  \n", x1)
print("x2  \n", x2)
print("x1 < 3 \n", x1<3)
print("x1 == 3 \n", x1==3)
print("x1 + x2 \n", x1+x2)
print("x1 * x2 \n", x1* x2)
print("x2 * x1 \n", x2* x1)

x1  
 [[1 2 3]
 [4 5 6]]
x2  
 [2 2 2]
x1 < 3 
 [[ True  True False]
 [False False False]]
x1 == 3 
 [[False False  True]
 [False False False]]
x1 + x2 
 [[3 4 5]
 [6 7 8]]
x1 * x2 
 [[ 2  4  6]
 [ 8 10 12]]
x2 * x1 
 [[ 2  4  6]
 [ 8 10 12]]


In [23]:
# Exemplo de métodos sobre arrays Numpy booleanos
print(x1)
print("Número de valores menores de 3 em x1 ", np.count_nonzero(x1 < 3))
print("Número de valores menores de 3 em x1 ", np.sum(x1 < 3))
print("Por que os valores dos dois comandos print() são iguais?")

print('porque ambos contabilizam os valores abaixo de 3')

[[1 2 3]
 [4 5 6]]
Número de valores menores de 3 em x1  2
Número de valores menores de 3 em x1  2
Por que os valores dos dois comandos print() são iguais?
porque ambos contabilizam os valores abaixo de 3


In [25]:
# Exemplo de uso dos métodos np.all(array_booleano) e np.any(array_booleano)
print("Explique o funcionamento desses dois métodos")
print(x1)
print(np.any(x1<3))
print(np.all(x1<3))

print("any = qualquer e all = todos, sendo assim como o vetor possui valores abaixo de 3. any = true e all = false")


Explique o funcionamento desses dois métodos
[[1 2 3]
 [4 5 6]]
True
False
any = qualquer e all = todos, sendo assim como o vetor possui valores abaixo de 3. any = true e all = false


### Métodos de funções estatísticas
Há diversos métodos que implementam funções estatísticas básicas para Arrays Numpy. Abaixo são apresentados alguns exemplos de uso dessas funções.

In [26]:
# Exemplos de uso de funções estatísticas

x = np.arange(1,10)
print("x = ", x)
print("valor mínimo de x = ", x.min())
print("valor mínimo de x = ", min(x))
print("valor máximo de x = ", x.max())
print("valor máximo de x = ", max(x))
print("soma dos elementos de x = ", x.sum())
print("soma dos elementos de x = ", sum(x))

x =  [1 2 3 4 5 6 7 8 9]
valor mínimo de x =  1
valor mínimo de x =  1
valor máximo de x =  9
valor máximo de x =  9
soma dos elementos de x =  45
soma dos elementos de x =  45


In [32]:
# Exemplos de uso de funções estatísticas
print("média dos valores dos elementos de x = ", x.mean())
print("desvio padrão dos valores dos elementos de x = ", x.std())

média dos valores dos elementos de x =  5.0
desvio padrão dos valores dos elementos de x =  2.581988897471611


In [34]:
print("Os dois comandos print() abaixo estão corretos?")
#print("média dos valores dos elementos de x = ", mean(x))
#print("desvio padrão dos valores dos elementos de x = ", std(x))

print('os comandos mencionados não estão corretos. O motivo é que as funções mean() e std() não estão diretamente disponíveis no escopo global do Python')

Os dois comandos print() abaixo estão corretos?
os comandos mencionados não estão corretos. O motivo é que as funções mean() e std() não estão diretamente disponíveis no escopo global do Python


In [35]:
# Exemplo de uso de funções estatísticas sobre Arrays Numpy
x = np.arange(1,10)
print("x = ", x)
print("valor mínimo de x = ", np.min(x))
print("valor máximo de x = ", np.max(x))
print("soma dos elementos de x = ", np.sum(x))
print("média dos valores dos elementos de x = ", np.mean(x))
print("mediana dos valores dos elementos de x = ", np.median(x))
print("desvio padrão dos valores dos elementos de x = ", np.std(x))
print("variância dos valores dos elementos de x = ", np.var(x))
print("desvio padrão dos valores dos elementos de x = ", np.sqrt(np.var(x)))

x =  [1 2 3 4 5 6 7 8 9]
valor mínimo de x =  1
valor máximo de x =  9
soma dos elementos de x =  45
média dos valores dos elementos de x =  5.0
mediana dos valores dos elementos de x =  5.0
desvio padrão dos valores dos elementos de x =  2.581988897471611
variância dos valores dos elementos de x =  6.666666666666667
desvio padrão dos valores dos elementos de x =  2.581988897471611


### Observação:
Como visto anteriormente, os métodos específicos do Numpy são mais eficientes computacionalmente do que métodos padrões.

A seguir verifique o desempenho de métodos estatísticos específicos do Numpy com relação aos métodos gerais.

In [36]:
# Exemplo - Avaliação de desempenho de método genérico e método específico do Numpy
big_array = np.random.rand(1000000)
print("Tempo de execução de uma soma de elementos de um array via método genérico")
%timeit sum(big_array)
print("Tempo de execução de uma soma de elementos de um array via método específico do numpy")
%timeit np.sum(big_array)

Tempo de execução de uma soma de elementos de um array via método genérico
114 ms ± 36.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
Tempo de execução de uma soma de elementos de um array via método específico do numpy
390 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [38]:
# Exercício - Avalie o desempenho dos métodos genérico e específico
# para cálculo de desvio padrão
# Utilize o Array big_array

## Escreva o código aqui

import math
big_array = np.random.rand(1000000)
print("Tempo de execução de desvio padrão de elementos de um array via método genérico")
%timeit n = len(big_array); mean = sum(big_array) / n; variance = sum((xi - mean) ** 2 for xi in big_array) / n

print("Tempo de execução de desvio padrão de elementos de um array via método específico do numpy")
%timeit np.std(big_array)




Tempo de execução de desvio padrão de elementos de um array via método genérico
543 ms ± 12.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
Tempo de execução de desvio padrão de elementos de um array via método específico do numpy
3.14 ms ± 551 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


### Observação
Para se realizar operações matriciais com Arrays Numpy é necessário utilizar métodos.
- np.dot(x,y) --> x*y
- x.dot(y) --> x*y
- np.inv
- np.mat.T  --> $mat^T$

In [41]:
# Exemplo de uso de métodos para operação matricial em Arrays Numpy
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
z1 = x.dot(y) 
z2 = np.dot(x, y)
print("z1 = \n", z1)
print("\nz2 = \n", z2)

z1 = 
 [[ 28.  64.]
 [ 67. 181.]]

z2 = 
 [[ 28.  64.]
 [ 67. 181.]]


O programa abaixo implementa a seguinte equação matricial:

$mat_2 = mat_1^T * mat_1$

In [42]:
import numpy as np

mat1 = np.array([[1., 2., 3.], [4.5, .5, 6.7], [7.3,1.8,2.7]]) 
mat2 = mat1.T.dot(mat1)
print("mat1 = \n", mat1)
print("mat2 = \n", mat2)

mat1 = 
 [[1.  2.  3. ]
 [4.5 0.5 6.7]
 [7.3 1.8 2.7]]
mat2 = 
 [[74.54 17.39 52.86]
 [17.39  7.49 14.21]
 [52.86 14.21 61.18]]


In [43]:
#from numpy.linalg import inv
np.linalg.inv(mat1)

array([[-0.140625  ,  0.        ,  0.15625   ],
       [ 0.48266807, -0.25210084,  0.08928571],
       [ 0.05842962,  0.16806723, -0.11160714]])

In [44]:
# Para evitar explicitar o caminho do método no pacote
from numpy.linalg import inv
inv(mat1)

array([[-0.140625  ,  0.        ,  0.15625   ],
       [ 0.48266807, -0.25210084,  0.08928571],
       [ 0.05842962,  0.16806723, -0.11160714]])

In [45]:
# A multiplicação de uma matriz por sua inversa é uma matriz Identidade
mat1.dot(inv(mat1))

array([[ 1.00000000e+00, -2.77555756e-17,  0.00000000e+00],
       [-1.41693380e-18,  1.00000000e+00, -1.42742960e-17],
       [ 8.18497930e-17, -6.22751150e-18,  1.00000000e+00]])

In [46]:
# A multiplicação de uma matriz por sua inversa é uma matriz Identidade
np.dot(mat1,inv(mat1))

array([[ 1.00000000e+00, -2.77555756e-17,  0.00000000e+00],
       [-1.41693380e-18,  1.00000000e+00, -1.42742960e-17],
       [ 8.18497930e-17, -6.22751150e-18,  1.00000000e+00]])

In [47]:
# O mesmo problema ocorre com o método determinante
print("Determinante de mat1 = ", np.linalg.det(mat1))

from numpy.linalg import det
print("Determinante de mat1 = ", det(mat1))

Determinante de mat1 =  76.15999999999995
Determinante de mat1 =  76.15999999999995


Exercício:

Calcule a seguinte expressão matricial (use os vetores e matrizes já definidos anteriormente)

$ mat_3 = mat_1 * (mat_2)^{-1} * mat_1^T$

In [50]:
# Resolução do exercício
# Utilize mat1 e mat2 definidos acima

mat = np.dot(mat1,inv(mat2))
mat3 = np.dot(mat,mat1.T)
print("Valor de mat3 = \n", mat3)

Valor de mat3 = 
 [[ 1.00000000e+00 -5.55403062e-17 -3.60851638e-16]
 [-8.32667268e-17  1.00000000e+00 -1.33903159e-16]
 [-2.63677968e-16 -2.57135583e-16  1.00000000e+00]]


Classe Matriz em Numpy
- O Pacote Numpy possui uma classe especial de Array (uni e bidimensonal) denominada de matriz.
- Esse tipo de classe possui métodos específicos
- Matrizes necessitam ser bidimensionais.
    - Para se utilizar estrutura com dimensão maior que 2, prezamos utilizar Arrays Numpy
- As operações sobre o "tipo" matriz são operações matriciais, como em Matlab.
    - Operações sobre Arrays são operações elemento a elemento.



In [51]:
# Exemplo de uso do tipo Matriz do Numpy
import numpy as np

x1 = np.array([1, 2, 3], float) # definição de um Array unidimensional de 03 posições float

x2 = np.matrix(x1) #  Transformando o tipo Array em tipo Matriz

x2

matrix([[1., 2., 3.]])

In [52]:
type(x2)

numpy.matrix

In [56]:
# Exemplo de uso do tipo Matriz do Numpy
print("Exemplo de uso do método Tranposta de Matriz")
x3 = np.array([[1,2,3],[4,5,6]],float)  # esse passo não é necessário
x4 = np.matrix(x3)
x5 = np.mat(x4).transpose() 
print(x3)
print(x5)



Exemplo de uso do método Tranposta de Matriz
[[1. 2. 3.]
 [4. 5. 6.]]
[[1. 4.]
 [2. 5.]
 [3. 6.]]


In [57]:
# Exemplo de uso do tipo Matriz do Numpy
print("Exemplo de uso do método 'Tranposta de Matriz'")
x4 = np.matrix([[1,2,3],[4,5,6]],float) # pode-se converter tipo Lista diretamente para tipo Matriz
x5 = x4.T
# x5 = np.mat(x4).T # transport matriz via método de classe
# x5 = np.mat(x4).transpose()   # método para transpor matriz
x5

Exemplo de uso do método 'Tranposta de Matriz'


matrix([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [58]:
# Outra opção para se inicializar Matrizes Numpy
np.matrix("[1 2 3; 4 5 6]")

matrix([[1, 2, 3],
        [4, 5, 6]])

In [60]:
# Exemplo de uso do tipo Matriz do Numpy
print("Exemplo de uso do criação de uma Matriz Identidade")
mat0 = np.eye(5)  # matriz identidade de ordem 5 - ainda é tipo array
#mat0 = np.identity(5)
print(4*mat0)

Exemplo de uso do criação de uma Matriz Identidade
[[4. 0. 0. 0. 0.]
 [0. 4. 0. 0. 0.]
 [0. 0. 4. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 4.]]


In [63]:
# Transformar Array Identidade para Matriz Identidade
print(type(mat0))
mat1 = np.matrix(mat0)
print(type(mat1))


<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [69]:
# Exercício

print("O que ocorre quando se multiplica um Array por uma Matriz?")
print("Escreva um programa para investigar isto.")

t = np.matrix("[1 2 3; 4 5 6]")
w = np.array([1,2,3])

print(t)
print(w)

x = np.multiply(t,w)
print(x)

y = np.dot(t,w)
print(y)

print('contanto que tenha as dimensoes compativeis é possivel fazer a uma multiplicação')

O que ocorre quando se multiplica um Array por uma Matriz?
Escreva um programa para investigar isto.
[[1 2 3]
 [4 5 6]]
[1 2 3]
[[ 1  4  9]
 [ 4 10 18]]
[[14 32]]
contanto que tenha as dimensoes compativeis é possivel fazer a uma multiplicação


In [76]:
# Exemplos de uso de operadores sobre tipo Matriz do Numpy
vet1 = np.matrix([1,2,3],float)   # vetor linha 1x3
vet2 = np.matrix([[2],[4],[6]],float)   # vetor coluna 3x1
mat1 = np.matrix ([[1,2,3],[4,5,6], [7,8,9]],float) # matriz 3x3
mat2 = np.eye(3)   # matriz identidade 3x3

print(mat1, '\n')
print(mat2, '\n')
print("2*mat1*mat2 = \n", 2*mat1*mat2)
print("\nvet1*mat1*vet2 = \n", vet1*mat1*vet2)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

2*mat1*mat2 = 
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

vet1*mat1*vet2 = 
 [[456.]]


### Exercício:

Calcule a seguinte expressão matricial (use os vetores e matrizes já definidos anteriormente)

$ mat3 = (mat1^T * mat1) * vet1^T$

In [82]:
# Solução do exercício
print(mat1, '\n')
print(mat1.T, '\n')
print(vet1.T, '\n')

mat = (mat1.T * mat1)
mat3 = mat * vet1.T
print("mat3 = \n")
print(mat3)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]] 

[[1.]
 [2.]
 [3.]] 

mat3 = 

[[492.]
 [588.]
 [684.]]


In [83]:
# Exemplo de uso de inversa de matriz
mat1 = np.matrix ([[1,2,3],[4.7,1.5,2.6], [-3,8.7,1.9]],float) # matriz 3x3
print("Matriz mat1 = \n", mat1)
print("\nMatriz inversa de mat1 = \n", mat1.I)

Matriz mat1 = 
 [[ 1.   2.   3. ]
 [ 4.7  1.5  2.6]
 [-3.   8.7  1.9]]

Matriz inversa de mat1 = 
 [[-0.23836508  0.26886906  0.00843984]
 [-0.20171208  0.1314203   0.13865445]
 [ 0.54726308 -0.17723656 -0.09524958]]


### Exercício:

Calcule a seguinte expressão matricial (use os vetores e matrizes já definidos anteriormente)

$ mat3 = vet1 * (mat1^T * mat1)^{-1} * vet1^T$

In [89]:
# Solução do exercício
mat3 = vet1 * np.linalg.inv(mat1.T.dot(mat1)) * vet1.T

print("mat3 = \n")
print(mat3)

mat3 = 

[[1.]]


### Outra forma de operação com matrizes 
A baixo são apresentadas duas abordagens via array e matriz para o seguinte cálculo matricial:
- $z = y^T * X * y $

In [92]:
# Geração do Array bidimensional X  (Matriz 4x4)
X = np.array([[ 8.82768214, 3.82222409, -1.14276475, 2.04411587],[ 3.82222409, 6.75272284, 0.83909108, 2.08293758],[-1.14276475, 0.83909108, 5.01690521, 0.79573241],[ 2.04411587, 2.08293758, 0.79573241, 6.24095859]])

y = X[:, :1]    # Obtenção do vetor y (array 4x1) 

print(y)
np.dot(y.T, np.dot(X, y))


[[ 8.82768214]
 [ 3.82222409]
 [-1.14276475]
 [ 2.04411587]]


array([[1195.46796121]])

In [93]:
# Versão da solução acima utilizando-se a classe Matriz
Xm = np.matrix(X)
ym = Xm[:, 0]
ym.T * Xm * ym

matrix([[1195.46796121]])

In [94]:
Xm.I * Xm

matrix([[ 1.00000000e+00,  5.51626200e-17, -4.56576503e-17,
          3.79527990e-17],
        [-9.53217120e-18,  1.00000000e+00, -6.94251400e-18,
          1.75847890e-17],
        [ 1.92086986e-17, -2.14834112e-18,  1.00000000e+00,
          1.39686684e-17],
        [-1.58123959e-18,  1.07244609e-16,  3.39946528e-17,
          1.00000000e+00]])

In [95]:
Xm.I * X

matrix([[ 1.00000000e+00,  5.51626200e-17, -4.56576503e-17,
          3.79527990e-17],
        [-9.53217120e-18,  1.00000000e+00, -6.94251400e-18,
          1.75847890e-17],
        [ 1.92086986e-17, -2.14834112e-18,  1.00000000e+00,
          1.39686684e-17],
        [-1.58123959e-18,  1.07244609e-16,  3.39946528e-17,
          1.00000000e+00]])

In [96]:
# Obs.: Para se fazer multiplicação elemento-a-elemento com Matrizes,
# precisamos utilizar o método multiply

np.multiply(Xm,Xm)

matrix([[77.92797196, 14.60939699,  1.30591127,  4.17840969],
        [14.60939699, 45.59926575,  0.70407384,  4.33862896],
        [ 1.30591127,  0.70407384, 25.16933789,  0.63319007],
        [ 4.17840969,  4.33862896,  0.63319007, 38.94956412]])